### PR TITLE
o-ffmpeg: Add -threads 0 for multicore

### PR DESCRIPTION
**Pull request by AfoHT**
- o-ffmpeg: Add -threads 0 to enable multicore

### CODE REVIEW

**Comment by hanatos** [comment]
interesting. this seems to be the default for my ffmpeg install. does it actually change matters for you?

i suppose explicitly adding it doesn't hurt.. thanks for the PR!

**Comment by AfoHT** [comment]
Hi, this does a difference, unsure if it matters what codec or other settings are in use but yesterday encoding to prores I saw only one core being used. 

Added contents of this PR locally and now all cores got really busy 😇 

It was in stark contrast to the rest of this really speedy program 👍

FFmpeg used is current default Arch package: 

```
$ ffmpeg -version
ffmpeg version n6.0 Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 13.2.1 (GCC) 20230801
configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libjxl --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpl --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-opencl --enable-opengl --enable-shared --enable-version3 --enable-vulkan
libavutil      58.  2.100 / 58.  2.100
libavcodec     60.  3.100 / 60.  3.100
libavformat    60.  3.100 / 60.  3.100
libavdevice    60.  1.100 / 60.  1.100
libavfilter     9.  3.100 /  9.  3.100
libswscale      7.  1.100 /  7.  1.100
libswresample   4. 10.100 /  4. 10.100
libpostproc    57.  1.100 / 57.  1.100
```

**Comment by hanatos** [comment]
right. speeding this part up needs some work. mid term i'd like to do encoding directly on the device, maybe like https://github.com/nvpro-samples/vk_video_samples/tree/main/vk_video_encoder

**Comment by AfoHT** [comment]
Just to clarify, the big speed contrast I referred to was between ffmpeg only utilizing one core and rest of vkdt experience 😇 But I get your point, ffmpeg even with all cores take a while... 

What you propose sound really awesome, exciting times! 

Thank you for your hard work creating such awesome tools!

**Pull request merged**
